name: Publish Public Release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          java-package: jdk
          cache: 'gradle'

      - name: Prepare Gradle secure file
        run: |
          echo 'signingKeystorePassword=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}' >> local.properties
          echo 'signingKeyAlias=${{ secrets.SIGNING_KEY_ALIAS }}' >> local.properties
          echo 'signingKeyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}' >> local.properties

      - name: Build AAB
        id: build_aab
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;34.0.0"
          bash ./gradlew :app:increaseVersionCode :app:bundleRelease --stacktrace

      - name: Commit version.properties
        id: commit_version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increased Version Code
          file_pattern: 'version.properties'
          branch: master

      - name: Build APK
        id: build_apk
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;34.0.0"
          bash ./gradlew :app:assembleRelease --stacktrace

      - name: Create Github release
        id: release_github
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') || contains(github.ref_name, '-dev') }}
          files: app/build/outputs/apk/release/app-release.apk
          generate_release_notes: true
          fail_on_unmatched_files: true

      - name: Create release notes
        id: release_notes
        run: |
          mkdir -p changelog
          echo "${{ fromJSON(steps.release_github.outputs.assets)[0].description }}" > changelog/whatsnew-en

      - name: Set release track
        id: release_track
        run: |
          cond=${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') || contains(github.ref_name, '-dev') }};
          if [ "$cond" = true ] ; then
          echo '::set-output name=release_track::beta';
          else
          echo '::set-output name=release_track::production';
          fi

      - name: Upload to Play Store
        id: upload_play_store
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_GOOGLE_CLOUD_JSON }}
          packageName: org.escalaralcoiaicomtat.android
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: ${{steps.release_track.outputs.release_track}}
          inAppUpdatePriority: 2
          # mappingFile: ./base/build/outputs/mapping/release/mapping.txt
          whatsNewDirectory: ./changelog
          status: completed
